import { Folder, FolderOpen, BookOpen, Book, Library, GraduationCap, NotebookPen, School, Brain, Lightbulb, Languages, Microscope, FlaskConical, Atom, Calculator, PenTool, Pencil, FileText, Scroll, Bookmark, Briefcase, Monitor, Laptop, Code, Terminal, Database, Settings, Wrench, Hammer, Camera, Headphones, Mic, Music, Video, Mail, MessageCircle, Calendar, Clock, AlarmClock, Timer, Sun, Moon, Cloud, CloudRain, Snowflake, Wind, Leaf, TreePine, Flower2, Mountain, Waves, Globe, House, Coffee, Apple, Heart, Smile, Dog, Cat, Bird, Star, Flag, Tag, Tags, Target, Check, CircleCheck, Circle, Triangle, Square, Diamond, Zap, Flame, Sparkles, Trophy, Award, Rocket, Compass, Map, MapPin, Palette, Brush, Image, ShoppingCart, Gift, Wallet, Coins, Gem, Car, Bike, Plane, TrainFront, Ship, Gamepad2, Dumbbell, Activity, Stethoscope, Cross, Shield, Lock, Key, Users, User, Bell, Archive, Package, Puzzle, Infinity as InfinityIcon, Link, QrCode, type LucideIcon } from 'lucide-react';
const icons: Record<string,LucideIcon> = {Folder, FolderOpen, BookOpen, Book, Library, GraduationCap, NotebookPen, School, Brain, Lightbulb, Languages, Microscope, FlaskConical, Atom, Calculator, PenTool, Pencil, FileText, Scroll, Bookmark, Briefcase, Monitor, Laptop, Code, Terminal, Database, Settings, Wrench, Hammer, Camera, Headphones, Mic, Music, Video, Mail, MessageCircle, Calendar, Clock, AlarmClock, Timer, Sun, Moon, Cloud, CloudRain, Snowflake, Wind, Leaf, TreePine, Flower2, Mountain, Waves, Globe, House, Coffee, Apple, Heart, Smile, Dog, Cat, Bird, Star, Flag, Tag, Tags, Target, Check, CircleCheck, Circle, Triangle, Square, Diamond, Zap, Flame, Sparkles, Trophy, Award, Rocket, Compass, Map, MapPin, Palette, Brush, Image, ShoppingCart, Gift, Wallet, Coins, Gem, Car, Bike, Plane, TrainFront, Ship, Gamepad2, Dumbbell, Activity, Stethoscope, Cross, Shield, Lock, Key, Users, User, Bell, Archive, Package, Puzzle, Infinity: InfinityIcon, Link, QrCode};
export const iconGroups: Record<string, string[]> = {
  '学习与知识': ['Folder','FolderOpen','BookOpen','Book','Library','GraduationCap','NotebookPen','School','Brain','Lightbulb','Languages','Microscope','FlaskConical','Atom','Calculator','PenTool','Pencil','FileText','Scroll','Bookmark'],
  '工作与工具': ['Briefcase','Monitor','Laptop','Code','Terminal','Database','Settings','Wrench','Hammer','Camera','Headphones','Mic','Music','Video','Mail','MessageCircle','Calendar','Clock','AlarmClock','Timer'],
  '自然与生活': ['Sun','Moon','Cloud','CloudRain','Snowflake','Wind','Leaf','TreePine','Flower2','Mountain','Waves','Globe','House','Coffee','Apple','Heart','Smile','Dog','Cat','Bird'],
  '标记与方向': ['Star','Flag','Tag','Tags','Target','Check','CircleCheck','Circle','Triangle','Square','Diamond','Zap','Flame','Sparkles','Trophy','Award','Rocket','Compass','Map','MapPin'],
  '更多': ['Palette','Brush','Image','ShoppingCart','Gift','Wallet','Coins','Gem','Car','Bike','Plane','TrainFront','Ship','Gamepad2','Dumbbell','Activity','Stethoscope','Cross','Shield','Lock','Key','Users','User','Bell','Archive','Package','Puzzle','Infinity','Link','QrCode'],
};
export function FolderIcon({name,color}: {name:string;color?:string|null}) {
  const Icon = (icons as Record<string,LucideIcon>)[name] ?? icons.Folder;
  return <Icon size={18} strokeWidth={1.8} aria-hidden="true" className="custom-folder-icon" style={{color:color ?? 'var(--theme-dark)'}}/>;
}
